//! The pre-refactor wire format, asserted against `vilsend-core`.
//!
//! These are the same fixtures the desktop shell pinned before Phase 2 moved
//! `TransferProgress`, `TransferStatus` and `ConnectionStatus` out of it. The
//! comparison is byte for byte, on pretty-printed JSON, so both the values and
//! the field order are held.
//!
//! The fixtures are generated by the desktop crate's `golden` module (see
//! `crates/desktop/src/golden.rs`). Regenerate with
//! `UPDATE_GOLDEN=1 cargo test -p vilsend golden`.

use std::collections::BTreeMap;
use std::path::PathBuf;

use serde_json::Value;

use vilsend_core::{ConnectionStatus, DomainEvent, TransferProgress, TransferStatus};

fn fixtures_dir() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    loop {
        let candidate = dir.join("tests").join("fixtures").join("golden-payloads");

        if candidate.is_dir() {
            return candidate;
        }

        assert!(
            dir.pop(),
            "could not find tests/fixtures/golden-payloads above {}",
            env!("CARGO_MANIFEST_DIR")
        );
    }
}

fn assert_fixture(name: &str, actual: String) {
    let path = fixtures_dir().join(name);

    let expected = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("could not read {}: {error}", path.display()));

    assert_eq!(
        expected,
        actual,
        "wire format for {name} changed — this is a breaking change for the webview"
    );
}

fn check_serialised<T: serde::Serialize>(name: &str, value: &T) {
    let mut json = serde_json::to_string_pretty(value).expect("value is serialisable");
    json.push('\n');

    assert_fixture(name, json);
}

fn variants<T, F>(entries: F) -> BTreeMap<String, Value>
where
    T: serde::Serialize,
    F: IntoIterator<Item = (&'static str, T)>,
{
    entries
        .into_iter()
        .map(|(name, value)| {
            (
                name.to_string(),
                serde_json::to_value(value).expect("variant is serialisable"),
            )
        })
        .collect()
}

#[test]
fn transfer_progress_wire_format_is_unchanged() {
    let uploading = TransferProgress {
        transfer_id: "8f14e45f-ea42-4d7e-9b3a-1b2c3d4e5f60".into(),
        uploaded_bytes: 512,
        total_bytes: 1024,
        percentage: 50.0,
        speed: 256.0,
        eta: Some(2),
        status: TransferStatus::Uploading,
    };

    let downloading = TransferProgress {
        transfer_id: "3c59dc04-8e88-4b0a-9f5e-6d7c8b9a0f11".into(),
        uploaded_bytes: 3_000_000,
        total_bytes: 12_000_000,
        percentage: 25.0,
        speed: 1_000_000.0,
        eta: Some(9),
        status: TransferStatus::Downloading,
    };

    let completed = TransferProgress {
        transfer_id: "8f14e45f-ea42-4d7e-9b3a-1b2c3d4e5f60".into(),
        uploaded_bytes: 1024,
        total_bytes: 1024,
        percentage: 100.0,
        speed: 0.0,
        eta: None,
        status: TransferStatus::Completed,
    };

    check_serialised("transfer-progress-uploading.json", &uploading);
    check_serialised("transfer-progress-downloading.json", &downloading);
    check_serialised("transfer-progress-completed.json", &completed);
}

#[test]
fn transfer_status_wire_format_is_unchanged() {
    let all = variants([
        ("Queued", TransferStatus::Queued),
        ("Uploading", TransferStatus::Uploading),
        ("Paused", TransferStatus::Paused),
        ("Completed", TransferStatus::Completed),
        ("Failed", TransferStatus::Failed),
        ("Cancelled", TransferStatus::Cancelled),
        ("Pending", TransferStatus::Pending),
        ("Downloading", TransferStatus::Downloading),
    ]);

    check_serialised("transfer-status.json", &all);
}

#[test]
fn connection_status_wire_format_is_unchanged() {
    let all = variants([
        ("Disconnected", ConnectionStatus::Disconnected),
        ("Connecting", ConnectionStatus::Connecting),
        ("Connected", ConnectionStatus::Connected),
        ("Reconnecting", ConnectionStatus::Reconnecting),
        ("Error", ConnectionStatus::Error("websocket closed".into())),
    ]);

    check_serialised("connection-status.json", &all);
}

#[test]
fn transfer_event_names_are_unchanged() {
    let progress = TransferProgress {
        transfer_id: "8f14e45f-ea42-4d7e-9b3a-1b2c3d4e5f60".into(),
        uploaded_bytes: 512,
        total_bytes: 1024,
        percentage: 50.0,
        speed: 256.0,
        eta: Some(2),
        status: TransferStatus::Uploading,
    };

    let names: Vec<&str> = vec![
        DomainEvent::TransferProgress {
            progress: progress.clone(),
        }
        .wire_name(),
        DomainEvent::TransferCompleted {
            progress: progress.clone(),
        }
        .wire_name(),
        DomainEvent::TransferFailed {
            progress: progress.clone(),
        }
        .wire_name(),
        DomainEvent::TransferPaused {
            progress: progress.clone(),
        }
        .wire_name(),
        DomainEvent::TransferResumed {
            progress: progress.clone(),
        }
        .wire_name(),
        DomainEvent::TransferCancelled { progress }.wire_name(),
    ];

    check_serialised("transfer-event-names.json", &names);
}

#[test]
fn every_event_payload_is_a_transfer_progress() {
    let progress = TransferProgress {
        transfer_id: "8f14e45f-ea42-4d7e-9b3a-1b2c3d4e5f60".into(),
        uploaded_bytes: 512,
        total_bytes: 1024,
        percentage: 50.0,
        speed: 256.0,
        eta: Some(2),
        status: TransferStatus::Uploading,
    };

    let event = DomainEvent::TransferProgress {
        progress: progress.clone(),
    };

    assert_eq!(event.progress(), &progress);
    check_serialised("transfer-progress-uploading.json", event.progress());
}
